/**
 * MIS Report Master FMS / workflow step catalog.
 * Extracted directly from MIS Report Master Google Sheet COUNTIFS formulas.
 * Layout: date | … | status (+2) | … | onTime (+4) | name (+5)
 */

export interface FmsStepDef {
  id: string;
  /** Master sheet parameter label */
  label: string;
  /** Section header shown above this step in Master */
  section: string;
  sheet: string;
  dateCol: number;
  endCol?: number;
  doneStatuses?: string[];
}

function step(
  id: string,
  section: string,
  label: string,
  sheet: string,
  dateCol: number,
  opts?: { endCol?: number; doneStatuses?: string[] },
): FmsStepDef {
  return {
    id,
    section,
    label,
    sheet,
    dateCol,
    endCol: opts?.endCol,
    doneStatuses: opts?.doneStatuses,
  };
}

/** Master-referenced steps (all tabs/columns matching MIS Report Master COUNTIFS). */
export const FMS_STEP_CATALOG: FmsStepDef[] = [
  step("alchemane-crm-web-app-0", "step 1", "step 1", "Alchemane CRM Web app", 0),
  step("alchemane-crm-web-app-7", "step 2", "step 2", "Alchemane CRM Web app", 7),
  step("alchemane-crm-web-app-14", "step 3", "step 3", "Alchemane CRM Web app", 14),
  step("enquiry-to-consutation-data-0", "Step1 (E)", "Step1 (E)", "Enquiry To Consutation Data", 0),
  step("enquiry-to-consutation-data-7", "Step2 (E)", "Step2 (E)", "Enquiry To Consutation Data", 7),
  step("enquiry-to-consutation-data-21", "Step 4 (R)", "Step 4 (R)", "Enquiry To Consutation Data", 21),
  step("alchemane-o2d-7", "Step 2", "Step 2", "Alchemane O2D", 7),
  step("alchemane-o2d-14", "Step 3", "Step 3", "Alchemane O2D", 14),
  step("cons2order-data-0", "Step 1", "Step 1", "Cons2Order Data", 0),
  step("alchemane-o2d-21", "Step 4", "Step 4", "Alchemane O2D", 21),
  step("cons2order-data-7", "Step 2", "Step 2", "Cons2Order Data", 7),
  step("alchemane-o2d-28", "Step 5", "Step 5", "Alchemane O2D", 28),
  step("cons2order-data-14", "Step 3 ", "Step 3 ", "Cons2Order Data", 14),
  step("alchemane-o2d-35", "Step 6", "Step 6", "Alchemane O2D", 35),
  step("cons2order-data-21", "Step 4 (Video)", "Step 4 (Video)", "Cons2Order Data", 21),
  step("alchemane-o2d-42", "Step 7", "Step 7", "Alchemane O2D", 42),
  step("cons2order-data-28", "Step 5 (Video)", "Step 5 (Video)", "Cons2Order Data", 28),
  step("cons2order-data-35", "Step 6 (Video)", "Step 6 (Video)", "Cons2Order Data", 35),
  step("help-slip-fms-0", "Step 1", "Step 1", "Help Slip FMS", 0),
  step("help-slip-fms-7", "Step 2", "Step 2", "Help Slip FMS", 7),
  step("help-slip-fms-14", "Step 3", "Step 3", "Help Slip FMS", 14),
  step("new-hair-refilling-fms-0", "Step 1", "Step 1", "New Hair Refilling FMS", 0),
  step("new-hair-refilling-fms-7", "Step 2", "Step 2", "New Hair Refilling FMS", 7),
  step("new-hair-refilling-fms-14", "Step 3", "Step 3", "New Hair Refilling FMS", 14),
  step("new-hair-refilling-fms-21", "Step 4", "Step 4", "New Hair Refilling FMS", 21),
  step("new-hair-refilling-fms-28", "Step 5", "Step 5", "New Hair Refilling FMS", 28),
  step("help-ticket-fms-0", "Step 1", "Step 1", "Help Ticket FMS", 0),
  step("hr-fms-v2-0-0", "Step 1", "Step 1", "HR FMS v2.0", 0),
  step("help-ticket-fms-7", "Step 2", "Step 2", "Help Ticket FMS", 7),
  step("hr-fms-v2-0-7", "Step 2", "Step 2", "HR FMS v2.0", 7),
  step("help-ticket-fms-14", "Step 3", "Step 3", "Help Ticket FMS", 14),
  step("hr-fms-v2-0-14", "Step 3", "Step 3", "HR FMS v2.0", 14),
  step("help-ticket-fms-21", "Step 4", "Step 4", "Help Ticket FMS", 21),
  step("hr-fms-v2-0-21", "Step 4", "Step 4", "HR FMS v2.0", 21),
  step("help-ticket-fms-28", "Step 5", "Step 5", "Help Ticket FMS", 28),
  step("hr-fms-v2-0-28", "Step 5", "Step 5", "HR FMS v2.0", 28),
  step("help-ticket-fms-42", "Step 6", "Step 6", "Help Ticket FMS", 42),
  step("hr-fms-v2-0-35", "Step 6", "Step 6", "HR FMS v2.0", 35),
  step("hr-fms-v2-0-42", "Step 7", "Step 7", "HR FMS v2.0", 42),
  step("new-joining-fms-0", "Step 1", "Step 1", "New Joining FMS", 0),
  step("new-joining-fms-7", "Step 2", "Step 2", "New Joining FMS", 7),
  step("blog-fms-alchemane--0", "Step 1", "Step 1", "Blog FMS (Alchemane)", 0),
  step("new-joining-fms-14", "Step 3", "Step 3", "New Joining FMS", 14),
  step("blog-fms-alchemane--7", "Step 2", "Step 2", "Blog FMS (Alchemane)", 7),
  step("new-joining-fms-21", "Step 4", "Step 4", "New Joining FMS", 21),
  step("blog-fms-alchemane--14", "Step 3", "Step 3", "Blog FMS (Alchemane)", 14),
  step("new-joining-fms-28", "Step 5", "Step 5", "New Joining FMS", 28),
  step("blog-fms-alchemane--21", "Step 4", "Step 4", "Blog FMS (Alchemane)", 21),
  step("blog-fms-alchemane--28", "Step 5", "Step 5", "Blog FMS (Alchemane)", 28),
  step("blog-fms-american--0", "Step 1", "Step 1", "Blog FMS (American)", 0),
  step("blog-fms-alchemane--35", "Step 6", "Step 6", "Blog FMS (Alchemane)", 35),
  step("blog-fms-american--7", "Step 2", "Step 2", "Blog FMS (American)", 7),
  step("blog-fms-alchemane--42", "Step 7", "Step 7", "Blog FMS (Alchemane)", 42),
  step("blog-fms-american--14", "Step 3", "Step 3", "Blog FMS (American)", 14),
  step("blog-fms-american--21", "Step 4", "Step 4", "Blog FMS (American)", 21),
  step("o2d-mumbai-v2-0-0", "Step 1", "Step 1", "O2D Mumbai v2.0", 0, { endCol: 1 }),
  step("blog-fms-american--28", "Step 5", "Step 5", "Blog FMS (American)", 28),
  step("o2d-mumbai-v2-0-7", "Step 2", "Step 2", "O2D Mumbai v2.0", 7, { endCol: 8 }),
  step("blog-fms-american--35", "Step 6", "Step 6", "Blog FMS (American)", 35),
  step("o2d-mumbai-v2-0-14", "Step 3", "Step 3", "O2D Mumbai v2.0", 14, { endCol: 15 }),
  step("blog-fms-american--42", "Step 7", "Step 7", "Blog FMS (American)", 42),
  step("o2d-mumbai-v2-0-21", "Step 4", "Step 4", "O2D Mumbai v2.0", 21, { endCol: 22 }),
  step("o2d-mumbai-v2-0-28", "Step 5", "Step 5", "O2D Mumbai v2.0", 28, { endCol: 29 }),
  step("o2d-mumbai-v2-0-35", "Step 6", "Step 6", "O2D Mumbai v2.0", 35, { endCol: 36 }),
  step("o2d-mumbai-v2-0-42", "Step 7", "Step 7", "O2D Mumbai v2.0", 42, { endCol: 43 }),
  step("o2d-mumbai-v2-0-49", "Step 8", "Step 8", "O2D Mumbai v2.0", 49, { endCol: 50 }),
  step("o2d-bangalore-v2-0-0", "Step 1", "Step 1", "O2D Bangalore v2.0", 0, { endCol: 1 }),
  step("o2d-bangalore-v2-0-7", "Step 2", "Step 2", "O2D Bangalore v2.0", 7, { endCol: 8 }),
  step("o2d-bangalore-v2-0-14", "Step 3", "Step 3", "O2D Bangalore v2.0", 14, { endCol: 15 }),
  step("o2d-bangalore-v2-0-21", "Step 4", "Step 4", "O2D Bangalore v2.0", 21, { endCol: 22 }),
  step("o2d-bangalore-v2-0-28", "Step 5", "Step 5", "O2D Bangalore v2.0", 28, { endCol: 29 }),
  step("custom-order-fms-0", "Step 1", "Step 1", "Custom Order FMS", 0),
  step("o2d-bangalore-v2-0-35", "Step 6", "Step 6", "O2D Bangalore v2.0", 35, { endCol: 36 }),
  step("custom-order-fms-7", "Step 2", "Step 2", "Custom Order FMS", 7),
  step("o2d-bangalore-v2-0-42", "Step 7", "Step 7", "O2D Bangalore v2.0", 42, { endCol: 43 }),
  step("custom-order-fms-14", "Step 3", "Step 3", "Custom Order FMS", 14),
  step("o2d-bangalore-v2-0-49", "Step 8", "Step 8", "O2D Bangalore v2.0", 49, { endCol: 50 }),
  step("custom-order-fms-21", "Step 4", "Step 4", "Custom Order FMS", 21),
  step("custom-order-fms-28", "Step 5", "Step 5", "Custom Order FMS", 28),
  step("smp-enqiury-fms-0", "Step 1", "Step 1", "SMP_Enqiury_FMS", 0),
  step("custom-order-fms-35", "Step 6", "Step 6", "Custom Order FMS", 35),
  step("smp-enqiury-fms-7", "Step 2", "Step 2", "SMP_Enqiury_FMS", 7),
  step("custom-order-fms-42", "Step 7", "Step 7", "Custom Order FMS", 42),
  step("smp-enqiury-fms-14", "Step 3", "Step 3", "SMP_Enqiury_FMS", 14),
  step("custom-order-fms-49", "Step 8", "Step 8", "Custom Order FMS", 49),
  step("smp-enqiury-fms-21", "Step 4", "Step 4", "SMP_Enqiury_FMS", 21),
  step("custom-order-fms-56", "Step 9", "Step 9", "Custom Order FMS", 56),
  step("custom-order-fms-63", "Step 10", "Step 10", "Custom Order FMS", 63),
  step("smp-session-fms-0", "Step 1", "Step 1", "SMP_Session_FMS", 0),
  step("smp-session-fms-7", "Step 2", "Step 2", "SMP_Session_FMS", 7),
  step("cons2order-data-42", "Step 1", "Step 1", "Cons2Order Data", 42),
  step("smp-session-fms-14", "Step 3", "Step 3", "SMP_Session_FMS", 14),
  step("cons2order-data-49", "Step 2", "Step 2", "Cons2Order Data", 49),
  step("smp-session-fms-21", "Step 4", "Step 4", "SMP_Session_FMS", 21),
  step("cons2order-data-56", "Step 3", "Step 3", "Cons2Order Data", 56),
  step("meeting-tie-up-fms-american-hairline-0", "Step 1", "Step 1", "Meeting Tie-up FMS | American Hairline", 0),
  step("meeting-tie-up-fms-american-hairline-7", "Step 2", "Step 2", "Meeting Tie-up FMS | American Hairline", 7),
  step("retention-service--0", "Step 1", "Step 1", "Retention (Service)", 0),
  step("meeting-tie-up-fms-american-hairline-14", "Step 3", "Step 3", "Meeting Tie-up FMS | American Hairline", 14),
  step("retention-service--7", "Step 2", "Step 2", "Retention (Service)", 7),
  step("meeting-tie-up-fms-american-hairline-21", "Step 4", "Step 4", "Meeting Tie-up FMS | American Hairline", 21),
  step("meeting-tie-up-fms-american-hairline-28", "Step 5", "Step 5", "Meeting Tie-up FMS | American Hairline", 28),
  step("product-retention-scot-american-hairline-0", "Step 1", "Step 1", "Product Retention (SCOT) | American Hairline", 0),
  step("meeting-tie-up-fms-american-hairline-35", "Step 6", "Step 6", "Meeting Tie-up FMS | American Hairline", 35),
  step("product-retention-scot-american-hairline-0-1", "Step 2", "Step 2", "Product Retention (SCOT) | American Hairline", 0),
  step("alchemane-crr-fms-client-servicing-0", "Step 1", "Step 1", "Alchemane CRR FMS | Client Servicing", 0),
  step("alchemane-crr-fms-client-servicing-7", "Step 2", "Step 2", "Alchemane CRR FMS | Client Servicing", 7),
  step("calcutta-fms-0", "Step 1", "Step 1", "Calcutta FMS", 0),
  step("delhi-bangalore-dispatch-fms-0", "Step 1", "Step 1", "Delhi/Bangalore Dispatch FMS", 0),
  step("calcutta-fms-7", "Step 2", "Step 2", "Calcutta FMS", 7),
  step("delhi-bangalore-dispatch-fms-7", "Step 2", "Step 2", "Delhi/Bangalore Dispatch FMS", 7),
  step("calcutta-fms-14", "Step 3", "Step 3", "Calcutta FMS", 14),
  step("delhi-bangalore-dispatch-fms-14", "Step 3", "Step 3", "Delhi/Bangalore Dispatch FMS", 14),
  step("calcutta-fms-21", "Step 4", "Step 4", "Calcutta FMS", 21),
  step("delhi-bangalore-dispatch-fms-21", "Step 4", "Step 4", "Delhi/Bangalore Dispatch FMS", 21),
  step("calcutta-fms-28", "Step 5", "Step 5", "Calcutta FMS", 28),
  step("delhi-bangalore-dispatch-fms-29", "Step 5", "Step 5", "Delhi/Bangalore Dispatch FMS", 29),
  step("calcutta-fms-35", "Step 6", "Step 6", "Calcutta FMS", 35),
  step("delhi-bangalore-dispatch-fms-36", "Step 6", "Step 6", "Delhi/Bangalore Dispatch FMS", 36),
  step("calcutta-fms-42", "Step 7", "Step 7", "Calcutta FMS", 42),
  step("delhi-bangalore-dispatch-fms-43", "Step 7", "Step 7", "Delhi/Bangalore Dispatch FMS", 43),
  step("calcutta-fms-49", "Step 8", "Step 8", "Calcutta FMS", 49),
  step("delhi-bangalore-dispatch-fms-50", "Step 8", "Step 8", "Delhi/Bangalore Dispatch FMS", 50),
  step("help-ticket-fms-alchemane-0", "Step 1", "Step 1", "Help Ticket FMS | Alchemane", 0),
  step("influencer-fms-0", "Step 1", "Step 1", "Influencer FMS", 0),
  step("help-ticket-fms-alchemane-7", "Step 2", "Step 2", "Help Ticket FMS | Alchemane", 7),
  step("influencer-fms-7", "Step 2", "Step 2", "Influencer FMS", 7),
  step("help-ticket-fms-alchemane-14", "Step 3", "Step 3", "Help Ticket FMS | Alchemane", 14),
  step("influencer-fms-14", "Step 3", "Step 3", "Influencer FMS", 14),
  step("influencer-fms-21", "Step 4", "Step 4", "Influencer FMS", 21),
  step("influencer-fms-29", "Step 5", "Step 5", "Influencer FMS", 29),
  step("help-ticket-fms-alchemane-35", "Step 6", "Step 6", "Help Ticket FMS | Alchemane", 35),
  step("influencer-fms-36", "Step 6", "Step 6", "Influencer FMS", 36),
  step("influencer-fms-43", "Step 7", "Step 7", "Influencer FMS", 43),
  step("inventory-delivery-from-mexico-0", "Step 1", "Step 1", "Inventory Delivery From Mexico", 0),
  step("influencer-fms-50", "Step 8", "Step 8", "Influencer FMS", 50),
  step("inventory-delivery-from-mexico-7", "Step 2", "Step 2", "Inventory Delivery From Mexico", 7),
  step("influencer-fms-58", "Step 9", "Step 9", "Influencer FMS", 58),
  step("inventory-delivery-from-mexico-14", "Step 3", "Step 3", "Inventory Delivery From Mexico", 14),
  step("influencer-fms-65", "Step 10", "Step 10", "Influencer FMS", 65),
  step("influencer-fms-72", "Step 11", "Step 11", "Influencer FMS", 72),
  step("inventory-delivery-from-mexico-28", "Step 5", "Step 5", "Inventory Delivery From Mexico", 28),
  step("influencer-fms-79", "Step 12", "Step 12", "Influencer FMS", 79),
  step("inventory-delivery-from-mexico-35", "Step 6", "Step 6", "Inventory Delivery From Mexico", 35),
  step("inventory-delivery-from-mexico-42", "Step 7", "Step 7", "Inventory Delivery From Mexico", 42),
  step("idea-to-upload-fms-0", "Step 1", "Step 1", "idea to Upload FMS", 0),
  step("inventory-delivery-from-mexico-49", "Step 8", "Step 8", "Inventory Delivery From Mexico", 49),
  step("idea-to-upload-fms-7", "Step 2", "Step 2", "idea to Upload FMS", 7),
  step("inventory-delivery-from-mexico-56", "Step 9", "Step 9", "Inventory Delivery From Mexico", 56),
  step("idea-to-upload-fms-14", "Step 3", "Step 3", "idea to Upload FMS", 14),
  step("idea-to-upload-fms-21", "Step 4", "Step 4", "idea to Upload FMS", 21),
  step("enquiry-fms-web-app--0", "Step 1", "Step 1", "Enquiry FMS (web app)", 0),
  step("idea-to-upload-fms-28", "Step 5", "Step 5", "idea to Upload FMS", 28),
  step("enquiry-fms-web-app--7", "Step 2", "Step 2", "Enquiry FMS (web app)", 7),
  step("idea-to-upload-fms-35", "Step 6", "Step 6", "idea to Upload FMS", 35),
  step("idea-to-upload-fms-42", "Step 7", "Step 7", "idea to Upload FMS", 42),
  step("local-custom-orders-0", "Step 1", "Step 1", "Local Custom Orders", 0),
  step("idea-to-upload-fms-49", "Step 8", "Step 8", "idea to Upload FMS", 49),
  step("local-custom-orders-7", "Step 2", "Step 2", "Local Custom Orders", 7),
  step("idea-to-upload-fms-56", "Step 9", "Step 9", "idea to Upload FMS", 56),
  step("local-custom-orders-14", "Step 3", "Step 3", "Local Custom Orders", 14, { doneStatuses: ["Completed"] }),
  step("local-custom-orders-21", "Step 4", "Step 4", "Local Custom Orders", 21),
  step("order-management-system-mexico-0", "Step 1", "Step 1", "Order Management System Mexico", 0),
  step("local-custom-orders-28", "Step 5", "Step 5", "Local Custom Orders", 28),
  step("order-management-system-mexico-7", "Step 2", "Step 2", "Order Management System Mexico", 7),
  step("local-custom-orders-35", "Step 6", "Step 6", "Local Custom Orders", 35),
  step("order-management-system-mexico-14", "Step 3", "Step 3", "Order Management System Mexico", 14),
  step("local-custom-orders-42", "Step 7", "Step 7", "Local Custom Orders", 42),
  step("order-management-system-mexico-21", "Step 4", "Step 4", "Order Management System Mexico", 21),
];
